# -*- coding: utf-8 -*-
"""SEO SILO clusters for AngelGranit — thematic architecture (no design)."""
from __future__ import annotations

BASE = "https://angelgranit.com"

# Popular money / intent services (link equity targets)
POPULAR_SERVICES = [
    ("uslugi/ritualnye-uslugi/", "Ритуальные услуги"),
    ("uslugi/organizaciya-pohoron/", "Организация похорон"),
    ("uslugi/pohorony-pod-klyuch/", "Похороны под ключ"),
    ("uslugi/katafalk/", "Катафалк"),
    ("uslugi/pamyatniki/", "Памятники"),
    ("uslugi/granitnye-pamyatniki/", "Гранитные памятники"),
    ("uslugi/memorialnye-kompleksy/", "Мемориальные комплексы"),
    ("uslugi/blagoustrojstvo-mogil/", "Благоустройство могил"),
]

SERVICE_TITLES = {
    "ritualnye-uslugi": "Ритуальные услуги",
    "organizaciya-pohoron": "Организация похорон",
    "pohorony-pod-klyuch": "Похороны под ключ",
    "katafalk": "Катафалк",
    "perevozka-umershih": "Перевозка умерших",
    "pamyatniki": "Памятники",
    "granitnye-pamyatniki": "Гранитные памятники",
    "mramornye-pamyatniki": "Мраморные памятники",
    "musulmanskie-pamyatniki": "Мусульманские памятники",
    "memorialnye-kompleksy": "Мемориальные комплексы",
    "blagoustrojstvo-mogil": "Благоустройство могил",
    "ogrady": "Ограды",
    "stoly": "Гранитные столы",
    "lavochki": "Лавочки",
    "cvetniki": "Цветники",
    "fotokeramika": "Фотокерамика",
    "gravirovka": "Гравировка",
    "venki": "Венки",
    "ritualnye-prinadlezhnosti": "Ритуальные принадлежности",
}

# Related services within silo (min 3 peers each)
SERVICE_PEERS: dict[str, list[str]] = {
    "ritualnye-uslugi": ["organizaciya-pohoron", "pohorony-pod-klyuch", "katafalk", "pamyatniki"],
    "organizaciya-pohoron": ["ritualnye-uslugi", "pohorony-pod-klyuch", "katafalk", "perevozka-umershih"],
    "pohorony-pod-klyuch": ["organizaciya-pohoron", "ritualnye-uslugi", "katafalk", "ritualnye-prinadlezhnosti"],
    "katafalk": ["perevozka-umershih", "organizaciya-pohoron", "pohorony-pod-klyuch", "ritualnye-uslugi"],
    "perevozka-umershih": ["katafalk", "organizaciya-pohoron", "ritualnye-uslugi"],
    "pamyatniki": ["granitnye-pamyatniki", "mramornye-pamyatniki", "memorialnye-kompleksy", "gravirovka"],
    "granitnye-pamyatniki": ["pamyatniki", "gravirovka", "fotokeramika", "memorialnye-kompleksy"],
    "mramornye-pamyatniki": ["pamyatniki", "granitnye-pamyatniki", "gravirovka"],
    "musulmanskie-pamyatniki": ["pamyatniki", "granitnye-pamyatniki", "blagoustrojstvo-mogil"],
    "memorialnye-kompleksy": ["pamyatniki", "blagoustrojstvo-mogil", "ogrady", "granitnye-pamyatniki"],
    "blagoustrojstvo-mogil": ["ogrady", "cvetniki", "stoly", "lavochki", "memorialnye-kompleksy"],
    "ogrady": ["blagoustrojstvo-mogil", "cvetniki", "memorialnye-kompleksy"],
    "stoly": ["lavochki", "blagoustrojstvo-mogil", "cvetniki"],
    "lavochki": ["stoly", "blagoustrojstvo-mogil", "ogrady"],
    "cvetniki": ["blagoustrojstvo-mogil", "ogrady", "stoly"],
    "fotokeramika": ["gravirovka", "granitnye-pamyatniki", "pamyatniki"],
    "gravirovka": ["fotokeramika", "granitnye-pamyatniki", "pamyatniki"],
    "venki": ["ritualnye-prinadlezhnosti", "pohorony-pod-klyuch", "organizaciya-pohoron"],
    "ritualnye-prinadlezhnosti": ["venki", "pohorony-pod-klyuch", "organizaciya-pohoron"],
}

# Article category → primary service silo
CAT_META = {
    "pervye-shagi": {
        "name": "Первые шаги после утраты",
        "cluster": "ritualnye-uslugi",
        "services": ["ritualnye-uslugi", "organizaciya-pohoron", "pohorony-pod-klyuch"],
    },
    "organizaciya-pohoron": {
        "name": "Организация похорон",
        "cluster": "ritualnye-uslugi",
        "services": ["organizaciya-pohoron", "pohorony-pod-klyuch", "ritualnye-uslugi"],
    },
    "dokumenty": {
        "name": "Документы",
        "cluster": "dokumenty",
        "services": ["organizaciya-pohoron", "ritualnye-uslugi", "perevozka-umershih"],
    },
    "transport": {
        "name": "Катафалк и перевозка",
        "cluster": "katafalk",
        "services": ["katafalk", "perevozka-umershih", "organizaciya-pohoron"],
    },
    "prinadlezhnosti": {
        "name": "Ритуальные принадлежности",
        "cluster": "prinadlezhnosti",
        "services": ["ritualnye-prinadlezhnosti", "venki", "pohorony-pod-klyuch"],
    },
    "pamyatniki": {
        "name": "Памятники",
        "cluster": "pamyatniki",
        "services": ["pamyatniki", "granitnye-pamyatniki", "mramornye-pamyatniki"],
    },
    "granit-i-gravirovka": {
        "name": "Гранит и гравировка",
        "cluster": "pamyatniki",
        "services": ["granitnye-pamyatniki", "gravirovka", "fotokeramika"],
    },
    "blagoustrojstvo": {
        "name": "Благоустройство",
        "cluster": "blagoustrojstvo",
        "services": ["blagoustrojstvo-mogil", "ogrady", "memorialnye-kompleksy"],
    },
    "tradicii": {
        "name": "Традиции и обряды",
        "cluster": "ritualnye-uslugi",
        "services": ["ritualnye-uslugi", "organizaciya-pohoron", "musulmanskie-pamyatniki"],
    },
    "ceny-i-byudzhet": {
        "name": "Цены и бюджет",
        "cluster": "ritualnye-uslugi",
        "services": ["pohorony-pod-klyuch", "ritualnye-uslugi", "pamyatniki"],
    },
}

# Full SILO map for strategy + /klastery/
CLUSTERS: list[dict] = [
    {
        "id": "home",
        "name": "Главная",
        "hub": "/",
        "role": "Brand + primary commercial entry: ритуальные услуги Алматы",
        "priority": 1.0,
        "traffic": "highest",
        "supporting": ["uslugi/", "temy/", "klastery/", "kontakty/"],
        "articles_cats": [],
        "anchors": ["#works", "#reviews", "#faq", "#packages", "#production"],
        "pillars": ["ritualnye-uslugi-almaty/", "organizaciya-pohoron-almaty/"],
    },
    {
        "id": "ritualnye-uslugi",
        "name": "Ритуальные услуги",
        "hub": "uslugi/ritualnye-uslugi/",
        "pillar": "ritualnye-uslugi-almaty/",
        "role": "Core commercial cluster — funerals organization 24/7",
        "priority": 0.98,
        "traffic": "highest",
        "services": [
            "uslugi/ritualnye-uslugi/",
            "uslugi/organizaciya-pohoron/",
            "uslugi/pohorony-pod-klyuch/",
        ],
        "supporting": [
            "ritualnye-uslugi-nedorogo-almaty/",
            "tseny-ritualnyh-uslug-almaty/",
            "ritualny-agent-almaty/",
            "kak-vybrat-ritualnoe-agentstvo/",
            "pravoslavnye-pohorony-almaty/",
            "korejskie-pohorony-almaty/",
            "svetskie-pohorony-almaty/",
            "proshchalnyj-zal-almaty/",
            "pominki-almaty/",
            "pominalnyj-obed-almaty/",
            "vyzov-batyushki-na-dom-almaty/",
            "ritualnye-uslugi-almatinskaya-oblast/",
        ],
        "articles_cats": ["pervye-shagi", "organizaciya-pohoron", "tradicii", "ceny-i-byudzhet"],
    },
    {
        "id": "pamyatniki",
        "name": "Памятники",
        "hub": "uslugi/pamyatniki/",
        "pillar": "pamyatniki-almaty/",
        "role": "Monument manufacturing & install — mid/long-term intent",
        "priority": 0.95,
        "traffic": "high",
        "services": [
            "uslugi/pamyatniki/",
            "uslugi/granitnye-pamyatniki/",
            "uslugi/mramornye-pamyatniki/",
            "uslugi/musulmanskie-pamyatniki/",
            "uslugi/gravirovka/",
            "uslugi/fotokeramika/",
        ],
        "supporting": [
            "granitnye-pamyatniki-almaty/",
            "kupit-pamyatnik-almaty/",
            "cena-granitnogo-pamyatnika-almaty/",
            "pravoslavnye-pamyatniki-almaty/",
            "epitafii-na-pamyatnik/",
            "krest-na-mogilu-almaty/",
        ],
        "articles_cats": ["pamyatniki", "granit-i-gravirovka"],
    },
    {
        "id": "memorialnye-kompleksy",
        "name": "Мемориальные комплексы",
        "hub": "uslugi/memorialnye-kompleksy/",
        "pillar": "memorialnye-kompleksy-almaty/",
        "role": "Premium project silo — full grave site design",
        "priority": 0.9,
        "traffic": "medium-high",
        "services": ["uslugi/memorialnye-kompleksy/", "uslugi/blagoustrojstvo-mogil/", "uslugi/pamyatniki/"],
        "supporting": ["memorialnye-kompleksy-almaty/"],
        "articles_cats": ["blagoustrojstvo", "pamyatniki"],
    },
    {
        "id": "blagoustrojstvo",
        "name": "Благоустройство",
        "hub": "uslugi/blagoustrojstvo-mogil/",
        "pillar": None,
        "role": "Aftercare / site improvement cluster",
        "priority": 0.88,
        "traffic": "medium",
        "services": [
            "uslugi/blagoustrojstvo-mogil/",
            "uslugi/ogrady/",
            "uslugi/stoly/",
            "uslugi/lavochki/",
            "uslugi/cvetniki/",
        ],
        "supporting": [],
        "articles_cats": ["blagoustrojstvo"],
    },
    {
        "id": "katafalk",
        "name": "Катафалк и перевозка",
        "hub": "uslugi/katafalk/",
        "pillar": "katafalk-almaty/",
        "role": "Urgent transport intent — high conversion",
        "priority": 0.94,
        "traffic": "high",
        "services": ["uslugi/katafalk/", "uslugi/perevozka-umershih/"],
        "supporting": [
            "katafalk-almaty/",
            "arenda-katafalka-almaty/",
            "as-almaty/",
            "gruz-200-almaty/",
            "gruz-200-avia-almaty/",
            "gruz-200-avto-almaty/",
            "gruz-200-dokumenty/",
        ],
        "articles_cats": ["transport"],
    },
    {
        "id": "prinadlezhnosti",
        "name": "Ритуальные принадлежности",
        "hub": "uslugi/ritualnye-prinadlezhnosti/",
        "pillar": "ritualnye-prinadlezhnosti-almaty/",
        "role": "Goods cluster — coffin, wreaths, cross",
        "priority": 0.85,
        "traffic": "medium",
        "services": ["uslugi/ritualnye-prinadlezhnosti/", "uslugi/venki/"],
        "supporting": ["ritualnye-prinadlezhnosti-almaty/", "grob-almaty/", "krest-na-mogilu-almaty/"],
        "articles_cats": ["prinadlezhnosti"],
    },
    {
        "id": "dokumenty",
        "name": "Документы",
        "hub": "stati/dokumenty/",
        "pillar": None,
        "role": "Informational — captures early research / trust",
        "priority": 0.82,
        "traffic": "medium-high",
        "services": ["uslugi/organizaciya-pohoron/", "uslugi/ritualnye-uslugi/"],
        "supporting": ["posobie-na-pogrebenie-almaty/", "gruz-200-dokumenty/"],
        "articles_cats": ["dokumenty", "pervye-shagi"],
    },
    {
        "id": "morg-zal",
        "name": "Морг и прощальный зал",
        "hub": "uslugi-morga-almaty/",
        "pillar": None,
        "role": "Supporting funeral logistics",
        "priority": 0.8,
        "traffic": "medium",
        "services": ["uslugi/organizaciya-pohoron/", "uslugi/ritualnye-uslugi/"],
        "supporting": [
            "uslugi-morga-almaty/",
            "holodilnaya-kamera-morg-almaty/",
            "balzamirovanie-almaty/",
            "omovenie-usopshogo-almaty/",
            "proshchalnyj-zal-almaty/",
            "kopka-mogily-almaty/",
        ],
        "articles_cats": ["organizaciya-pohoron", "pervye-shagi"],
    },
    {
        "id": "kladbishcha",
        "name": "Кладбища",
        "hub": "kladbishcha-almaty/",
        "pillar": None,
        "role": "Local geo + cemetery intent",
        "priority": 0.78,
        "traffic": "medium",
        "services": ["uslugi/organizaciya-pohoron/", "uslugi/katafalk/", "uslugi/pamyatniki/"],
        "supporting": [
            "kladbishcha-almaty/",
            "kladbishche-batajskoe-almaty/",
            "kladbishche-kensaj-almaty/",
        ],
        "articles_cats": ["organizaciya-pohoron", "blagoustrojstvo"],
    },
    {
        "id": "stati",
        "name": "Полезные статьи",
        "hub": "stati/",
        "pillar": None,
        "role": "Content silo — topical authority & long-tail",
        "priority": 0.9,
        "traffic": "high (long-tail)",
        "services": ["uslugi/"],
        "supporting": ["temy/", "seo/"],
        "articles_cats": list(CAT_META.keys()),
    },
    {
        "id": "faq-trust",
        "name": "FAQ / Отзывы / Работы",
        "hub": "/#faq",
        "pillar": None,
        "role": "Trust & UX anchors on homepage (E-E-A-T)",
        "priority": 0.75,
        "traffic": "assisted",
        "services": [],
        "supporting": ["/#faq", "/#reviews", "/#works", "/#guarantees", "/#why-us", "seo/faq/"],
        "articles_cats": [],
    },
    {
        "id": "geo",
        "name": "Районы и населённые пункты",
        "hub": "rajony/",
        "pillar": None,
        "role": "Local SEO silo",
        "priority": 0.8,
        "traffic": "medium",
        "services": ["uslugi/ritualnye-uslugi/", "uslugi/katafalk/", "uslugi/pamyatniki/"],
        "supporting": ["naselennye-punkty/", "ritualnye-uslugi-almatinskaya-oblast/"],
        "articles_cats": ["pervye-shagi", "organizaciya-pohoron"],
    },
    {
        "id": "kontakty",
        "name": "Контакты",
        "hub": "kontakty/",
        "pillar": None,
        "role": "Conversion endpoint — every commercial page links here",
        "priority": 0.92,
        "traffic": "brand / direct",
        "services": [],
        "supporting": ["kontakty/"],
        "articles_cats": [],
    },
]

# Theme page → cluster id
THEME_CLUSTER: dict[str, str] = {
    "ritualnye-uslugi-almaty": "ritualnye-uslugi",
    "organizaciya-pohoron-almaty": "ritualnye-uslugi",
    "ritualnye-uslugi-nedorogo-almaty": "ritualnye-uslugi",
    "tseny-ritualnyh-uslug-almaty": "ritualnye-uslugi",
    "ritualny-agent-almaty": "ritualnye-uslugi",
    "kak-vybrat-ritualnoe-agentstvo": "ritualnye-uslugi",
    "pravoslavnye-pohorony-almaty": "ritualnye-uslugi",
    "korejskie-pohorony-almaty": "ritualnye-uslugi",
    "svetskie-pohorony-almaty": "ritualnye-uslugi",
    "pominki-almaty": "ritualnye-uslugi",
    "pominalnyj-obed-almaty": "ritualnye-uslugi",
    "vyzov-batyushki-na-dom-almaty": "ritualnye-uslugi",
    "ritualnye-uslugi-almatinskaya-oblast": "ritualnye-uslugi",
    "pamyatniki-almaty": "pamyatniki",
    "granitnye-pamyatniki-almaty": "pamyatniki",
    "kupit-pamyatnik-almaty": "pamyatniki",
    "cena-granitnogo-pamyatnika-almaty": "pamyatniki",
    "pravoslavnye-pamyatniki-almaty": "pamyatniki",
    "epitafii-na-pamyatnik": "pamyatniki",
    "memorialnye-kompleksy-almaty": "memorialnye-kompleksy",
    "katafalk-almaty": "katafalk",
    "arenda-katafalka-almaty": "katafalk",
    "as-almaty": "katafalk",
    "gruz-200-almaty": "katafalk",
    "gruz-200-avia-almaty": "katafalk",
    "gruz-200-avto-almaty": "katafalk",
    "gruz-200-dokumenty": "katafalk",
    "ritualnye-prinadlezhnosti-almaty": "prinadlezhnosti",
    "grob-almaty": "prinadlezhnosti",
    "krest-na-mogilu-almaty": "prinadlezhnosti",
    "uslugi-morga-almaty": "morg-zal",
    "holodilnaya-kamera-morg-almaty": "morg-zal",
    "balzamirovanie-almaty": "morg-zal",
    "omovenie-usopshogo-almaty": "morg-zal",
    "proshchalnyj-zal-almaty": "morg-zal",
    "kopka-mogily-almaty": "morg-zal",
    "kladbishcha-almaty": "kladbishcha",
    "kladbishche-batajskoe-almaty": "kladbishcha",
    "kladbishche-kensaj-almaty": "kladbishcha",
    "posobie-na-pogrebenie-almaty": "dokumenty",
}
